%{?!ros_distro:%global ros_distro rolling}
%global pkg_name visp
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-visp
Version:        3.7.0
Release:        5%{?dist}
Summary:        ROS %{pkg_name} package

License:        GPL-2.0-or-later
URL:            https://visp.inria.fr
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%global __brp_check_rpaths QA_RPATHS=0x0002 %{__brp_check_rpaths}

%{?bloom_package}

%description
ViSP standing for Visual Servoing Platform is a modular cross platform library
that allows prototyping and developing applications using visual tracking and
visual servoing technics at the heart of the researches done by Inria Lagadic
team. ViSP is able to compute control laws that can be applied to robotic
systems. It provides a set of visual features that can be tracked using real
time image processing or computer vision algorithms. ViSP provides also
simulation capabilities. ViSP can be useful in robotics, computer vision,
augmented reality and computer animation.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
ViSP standing for Visual Servoing Platform is a modular cross platform library
that allows prototyping and developing applications using visual tracking and
visual servoing technics at the heart of the researches done by Inria Lagadic
team. ViSP is able to compute control laws that can be applied to robotic
systems. It provides a set of visual features that can be tracked using real
time image processing or computer vision algorithms. ViSP provides also
simulation capabilities. ViSP can be useful in robotics, computer vision,
augmented reality and computer animation.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
ViSP standing for Visual Servoing Platform is a modular cross platform library
that allows prototyping and developing applications using visual tracking and
visual servoing technics at the heart of the researches done by Inria Lagadic
team. ViSP is able to compute control laws that can be applied to robotic
systems. It provides a set of visual features that can be tracked using real
time image processing or computer vision algorithms. ViSP provides also
simulation capabilities. ViSP can be useful in robotics, computer vision,
augmented reality and computer animation.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 28 2026 Fabien Spindler <Fabien.Spindler@inria.fr> - 3.7.0-5
- Autogenerated by Bloom

* Tue Apr 21 2026 Fabien Spindler <Fabien.Spindler@inria.fr> - 3.7.0-4
- Autogenerated by Bloom
